In [167]:
import numpy as np
%matplotlib inline
from matplotlib import pylab as plt
import re
from scipy import spatial

In [168]:
f = open('sentences.txt', 'r')

In [169]:
a = []

In [170]:
for line in f:
    print line
    a.append(line)
print len(a)

In comparison to dogs, cats have not undergone major changes during the domestication process.

As cat simply catenates streams of bytes, it can be also used to concatenate binary files, where it will just concatenate sequence of bytes.

A common interactive use of cat for a single file is to output the content of a file to standard output.

Cats can hear sounds too faint or too high in frequency for human ears, such as those made by mice and other small animals.

In one, people deliberately tamed cats in a process of artificial selection, as they were useful predators of vermin.

The domesticated cat and its closest wild ancestor are both diploid organisms that possess 38 chromosomes and roughly 20,000 genes.

Domestic cats are similar in size to the other members of the genus Felis, typically weighing between 4 and 5 kg (8.8 and 11.0 lb).

However, if the output is piped or redirected, cat is unnecessary.

cat with one named file is safer where human error is a concern - one wrong us

In [171]:
for i in range(len(a)):
    a[i]=a[i].lower()
print len(a)

22


In [172]:
b =[]
for i in range(len(a)):
    b.append([])
    b[i].append(re.split('[^a-z]',a[i])) #Разделяем строку на слова,считая каждый элемент не являющийся буквой разделителем 

In [173]:
for i in range(len(b)):
    for j in range(b[i][0].count('')):
        b[i][0].remove('')

In [174]:
len(b)

22

In [175]:
dictionary  = {}
code = []

In [176]:
k = 0
for i in range(len(b)):
    for j in range(len(b[i][0])):
        if dictionary.get(b[i][0][j]) == None:
            dictionary[b[i][0][j]] = 1
            code.append(b[i][0][j])

In [177]:
A = np.zeros((len(b),len(code)))

In [178]:
for i in range(len(b)):
    for j in range(len(code)):
        A[[i],[j]] = b[i][0].count(code[j])

In [179]:
print A

[[1. 1. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 2. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 1. 1. 1.]]


In [180]:
check = np.zeros(len(b))

In [181]:
check[0] = 0

In [182]:
for i in range(1,len(b),1):
    check[i] = scipy.spatial.distance.cosine(A[0],A[i])

In [184]:
print check

[0.         0.95275444 0.86447381 0.89517152 0.77708871 0.94023857
 0.73273876 0.92587507 0.88427249 0.90550888 0.83281654 0.88047714
 0.83964325 0.87035926 0.87401184 0.94427218 0.84063619 0.9566445
 0.94427218 0.88854436 0.84275727 0.82503645]


In [186]:
g = open('submission-1.txt','w')

In [187]:
g.write('4 6')

In [190]:
g = open('submission-1.txt','r')
r = []
for line in g:
    r = line
    print line

4 6


In [191]:
r

'4 6'

In [192]:
r.count('\n')

0